<?php
$this->breadcrumbs=array(
	'Historia Clinicas'=>array('index'),
	$model->id_historia_clinica,
);

$this->menu=array(
array('label'=>'List HistoriaClinica','url'=>array('index')),
array('label'=>'Create HistoriaClinica','url'=>array('create')),
array('label'=>'Update HistoriaClinica','url'=>array('update','id'=>$model->id_historia_clinica)),
array('label'=>'Delete HistoriaClinica','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id_historia_clinica),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage HistoriaClinica','url'=>array('admin')),
);
?>

<h1>View HistoriaClinica #<?php echo $model->id_historia_clinica; ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'id_historia_clinica',
		'paciente',
		'peso',
		'talla',
		'frecuencia_cardiaca',
		'frecuencia_respiratoria',
		'tension_alta',
		'pulso',
		'circunferencia_cefalica',
		'circunferencia_abdominal',
		'otros',
		'alergico',
		'medicacion',
		'enfermedades',
		'observacion',
		'comentarios',
		'impresion_diagnostica',
		'tratamiento',
		'evolucion',
		'laboratorio',
		'examenes_otros',
		'estatus',
		'fecha_creacion',
		'fecha_actualizacion',
		'fk_usuario_creacion',
		'fk_usuario_actualizacion',
		'imageneologia',
		'plan_tratamiento',
		'examen_fisico',
		'motivo_consulta',
		'enfermedad_actual',
		'antecedentes_personales',
		'padre',
		'madre',
		'hermanos',
		'otros_hp',
		'fumar',
		'alcohol',
		'cafe',
		'drogas',
		'm_mejillas',
		'm_labios',
		'm_unas',
		'otros_habitosp',
		'FRS',
		'FUR',
		'PRS',
		'CICLO',
		'sinusorragia',
		'orgasmos',
		'maridos',
		'infeccion_ur',
		'dispareunia',
		'libido',
		'AVM',
		'DIU',
		'EIP',
		'ACO',
		'lactancia',
		'puerperio',
		'gestas',
),
)); ?>
